config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :libraries do
	resources :books
	resources :workers
	resources :subscribers
	resources :issues
  end
 
  root 'libraries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library.rb
class Library < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :books, dependent: :destroy
	has_many :workers, dependent: :destroy
	has_many :subscribers, dependent: :destroy
	validates :number, presence: true
	validates :name, presence: true
	validates :address, presence: true
	validates :avatar, presence: true
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
	def index
    	@libraries = Library.all
	end

	def show
		@library = Library.find(params[:id])
	end

	def new
		@library = Library.new
	end

	def edit
	  @library = Library.find(params[:id])
	end

	def create
		@library = Library.new(library_params)
 
		if @library.save
		    redirect_to @library
		else
			render 'new'
		end
	end

	def update
	  @library = Library.find(params[:id])
	 
	  if @library.update(library_params)
	    redirect_to @library
	  else
	    render 'edit'
	  end
	end
	
	def destroy
		@library = Library.find(params[:id])
		@library.destroy
		 
		redirect_to libraries_path
	end

	private
	  def library_params
	    params.require(:library).permit(:number, :name, :address, :avatar)
	  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for @library, {:multipart => true, :class => "form-horizontal"} do |f| %>
  <% if @library.errors.any? %>   
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
      <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= t('validate_errors.error', count: @library.errors.count)%></h3> <% @library.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </div>     
  <% end %>
 
  <div class="form-group">
    <%= f.label :number %> <span class="text-danger">*</span>
    <%= f.text_field :number, class: "form-control", placeholder: "Введите номер библиотеки" %>
  </div>
  <div class="form-group">
    <%= f.label :name %> <span class="text-danger">*</span>
    <%= f.text_area :name, class: "form-control", placeholder: "Введите название библиотеки" %>
  </div>
  <div class="form-group">
    <%= f.label :address %> <span class="text-danger">*</span>
    <%= f.text_area :address, size: "24х6", class: "form-control", placeholder: "Введите адрес библиотеки" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %> <span class="text-danger">*</span>
    <%= image_tag(@library.avatar_url, class:"img-responsive", style:"width: 200px;") if @library.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </div>
  <p>
    <%= f.submit 'Добавить', class: "btn btn-success" %>
  </p>
<% end %>

app/views/libraries/_imgform.html.erb
<%= form_for @library, :html => {:multipart => true} do |f| %>   
  <p>
    <label>My Avatar</label>
    <%= image_tag(@library.avatar_url) if @library.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
    <%= f.submit 'Добавить', class: "btn btn-success" %>
<% end %>

app/views/libraries/edit.html.erb
<div class="card">
  	<div class="card-body">
		<div class="row">
	      <div class="col-md-8">
	        <h2>Редактировать библиотеку</h2>
	      </div>
	      <div class="col-md-4 text-right">
	        <%= link_to 'Назад к библиотеке', library_path(@library), class:'right btn waves-effect waves-light btn-primary' %>
	      </div>
	    </div>
		<%= render 'form' %>
	</div>
</div>

app/views/libraries/index.html.erb
<div class="row">
  <% @libraries.each do |library| %>
    <!-- .col -->
    <div class="col-md-6 col-lg-6 col-xlg-4">
        <div class="card card-body">
            <div class="row">
                <div class="col-md-4 col-lg-3 text-center">
                    <%= link_to library_path(library) do %><img src="<%=library.avatar_url%>" alt="<%= library.name %>" class="img-circle img-responsive libraryavatar"><% end %>
                </div>
                <div class="col-md-8 col-lg-9">
                    <%= link_to library_path(library) do %><h3 class="box-title m-b-0"><%= library.name %></h3><% end %>
                    <p>
                        <%= library.number %> <%= library.address %>
                    </p>
                </div>
            </div>
        </div>
    </div>
  <% end %>
  <!-- .col -->
    <div class="col-md-6 col-lg-6 col-xlg-4">
        <div class="card card-body text-center">
            <%= link_to 'Добавить новую Бибилиотеку', new_library_path %>
        </div>
    </div>
</div>

app/views/libraries/new.html.erb
<div class="card">
  	<div class="card-body">
  		<div class="row">
	      <div class="col-md-8">
	        <h2>Добавить новую библиотеку</h2>
	      </div>
	      <div class="col-md-4 text-right">
	        <%= link_to 'Назад', libraries_path, class:'btn waves-effect waves-light btn-primary' %>
	      </div>
	    </div>
		<%= render 'form' %>
	</div>
</div>

app/views/libraries/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-9">
        <h3><%= @library.number %> | <%= @library.name %></h3>
        <p><%= @library.address %></p>
      </div>
      <div class="col-md-3 text-right">
        <%= link_to '', edit_library_path(@library), class: "btn btn-outline-success ti-pencil", data: { pack: 'default' }  %> <%= link_to '', library_path(@library), class: "btn btn-outline-danger ti-trash",
                    method: :delete,
                    data: { confirm: 'Вы уверены, что хотите удалить: "'+@library.name+'" и все что с ней связано?', pack: 'default' } %>
      </div>
    </div>
    <%= link_to 'Книжный фонд Библиотеки №'+@library.number, library_books_path(@library),class: "btn waves-effect waves-light btn-outline-info"%>
    <%= link_to 'Читатели Библиотеки №'+@library.number, library_subscribers_path(@library),class: "btn waves-effect waves-light btn-outline-info"%>
    
    <%= link_to 'Назад к Библиотекам', libraries_path, class: 'pull-right btn waves-effect waves-light btn-outline-primary' %>
  </div>
</div>
<div class="row el-element-overlay">
  <div class="col-md-12">
      <h4 class="card-title">Сотрудники</h4>
      <h6 class="card-subtitle m-b-20 text-muted"><%= @library.name %></h6>
  </div>
  <% @library.workers.each do |worker| %>
  <div class="col-lg-3 col-md-6">
      <div class="card">
          <div class="el-card-item">
              <div class="el-card-avatar el-overlay-1"> <img src="<%=worker.avatar_url%>" alt="<%= worker.fname+' '+worker.sname %>">
                  <div class="el-overlay">
                      <ul class="el-info">
                          <li><%= link_to ('<i class="icon-magnifier"></i>').html_safe, edit_library_worker_path(@library,worker), class: "btn default btn-outline image-popup-vertical-fit" %>
                          </li>
                          
                      </ul>
                  </div>
              </div>
              <div class="el-card-content">
                  <h3 class="box-title"><%= worker.fname+' '+worker.sname %></h3> <small><%= worker.post %></small>
                  <br> </div>
          </div>
      </div>
  </div>
  <% end %>
  <div class="col-lg-3 col-md-6">
      <div class="card">
              <div class="card-body text-center">
                  <%= link_to 'Добавить сотрудника', new_library_worker_path(@library) %>
              </div>
          </div>
      </div>
  </div>
</div>