config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :libraries do
	resources :books
	resources :workers
	resources :subscribers
	resources :issues
  end
 
  root 'libraries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library
  has_many :issues
  has_many :subscribers, through: :issues
  validates :name, presence: true
  validates :cipher, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@library = Library.find(params[:library_id])
    	@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
		@book_issues = Issue.where(book_id: params[:id])
		@issue = Issue.new
	end

	def new
		@library = Library.find(params[:library_id])
		@book = Book.new
	end

	def edit
	  @book = Book.find(params[:id])
	end

	def create
    	@library = Library.find(params[:library_id])
    	@book = @library.books.create(book_params)
    	if @book.valid?
    		redirect_to library_books_path(@library)
    	else
			render 'new'
		end
  	end

  	def update
	  @book = Book.find(params[:id])
	  if @book.update(book_params)
	    redirect_to library_book_path(@book.library,@book)
	  else
	    render 'edit'
	  end
	end
 	
 	def destroy
		@library = Library.find(params[:library_id])
		@book = @library.books.find(params[:id])
		@book.destroy
		redirect_to library_books_path(@library)
	end
  private
    def book_params
      params.require(:book).permit(:name, :author, :cipher, :publ, :publ_y, :price, :date)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for([@library, @library.books.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </p>
  <p>
    <%= f.label :cipher %><br>
    <%= f.text_field :cipher %>
  </p>
  <p>
    <%= f.label :publ %><br>
    <%= f.text_field :publ %>
  </p>
  <p>
    <%= f.label :publ_y %><br>
    <%= f.text_field :publ_y %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <%= link_to 'Назад', library_book_path(@book.library,@book), class:'pull-right btn btn-primary btn-xs' %>
                <h4 class="m-b-0 text-white">Редактировать книгу <%=@book.name%></h4>
            </div>
            <div class="card-body">
                <%= form_for ([@book.library, @book]), {:multipart => true} do |f| %>
                    <% if @book.errors.any? %>   
                        <div class="alert alert-warning">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                          <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= t('validate_errors.error', count: @book.errors.count)%></h3> <% @book.errors.full_messages.each do |msg| %>
                              <li><%= msg %></li>
                            <% end %>
                        </div>     
                      <% end %>
                  <div class="row p-t-20">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :name, class: 'control-label' %> <span class="text-danger">*</span> / <%= f.label :author, class: 'control-label' %>
                            <%= f.text_field :name, class: 'form-control', placeholder: "Название" %>
                            <small class="form-control-feedback"> Введите Название книги </small>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            
                            <%= f.text_field :author, class: 'form-control', placeholder: "Автор" %>
                            <small class="form-control-feedback"> Введите Авторов книги </small>
                        </div>
                    </div>
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :cipher, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :cipher, class: 'form-control', placeholder: "Шифр" %>
                            <small class="form-control-feedback"> Введите Шифр книги </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :price, class: 'control-label' %>
                            <%= f.text_field :price, class: 'form-control', placeholder: "00.00" %>
                            <small class="form-control-feedback"> Введите Цену книги </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :date, class: 'control-label' %>
                            <%= f.date_field :date, class: 'form-control', placeholder: "дд.мм.гггг" %>
                            <small class="form-control-feedback"> Введите Дату поступления книги в библиотеку </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :publ, class: 'control-label' %>
                            <%= f.text_field :publ, class: 'form-control', placeholder: "Издательство" %>
                            <small class="form-control-feedback"> Введите Название издательства </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :publ_y, class: 'control-label' %>
                            <%= f.number_field :publ_y, class: 'form-control', placeholder: "гггг", min: 1000, max: 2100, step: 1 %>
                            <small class="form-control-feedback"> Введите Год издания </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="form-actions">
                    <%= f.submit 'Сохранить',class: "pull-right btn btn-success" %>
                    <%= link_to 'Назад', library_book_path(@book.library,@book), class:'btn btn-primary' %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-10">
        <h2>Книжный фонд Библиотеки №<%=@library.number%></h2>
      </div>
      <div class="col-md-2 text-right">
        <%= link_to '', new_library_book_path(@library), class: "btn btn-outline-success ti-plus" %>
        <%= link_to 'Назад', library_path(@library), class:'btn btn-outline-primary' %>
      </div>
    </div>

    <div class="table-responsive m-t-40">
      <table id="TableDataodel" class="table table-bordered table-striped table-sm">
          <thead>
              <tr>
                  <th class="text-center" data-searchable="false">#</th>
                  <th class="text-center">Шифр</th>
                  <th>Название</th>
                  <th>Автор</th>
                  <th class="text-center">Издательство</th>
                  <th class="text-center">Год издания</th>
                  <th class="text-center" data-orderable="false" data-searchable="false"></th>
              </tr>
          </thead>
          <tbody>
              <% @library.books.each do |book| %>
                <tr>
                  <td class="text-center"><%= book.id %></td>
                  <td class="text-center"><%= book.cipher %></td>
                  <td><%= book.name %></td>
                  <td><%= book.author %></td>
                  <td class="text-center"><%= book.publ %></td>
                  <td class="text-center"><%= book.publ_y %></td>
                  <td class="text-center"><%= link_to '', library_book_path(@library,book), class: "btn btn-outline-info ti-book", target:'_blank'  %>
                
                  <%= link_to '', [book.library, book], class: "btn btn-outline-danger ti-trash",
                          method: :delete,
                          data: { confirm: 'Вы уверены, что хотите удалить: "'+book.name+'" и все что с ней связано?'} %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <%= link_to 'Назад', library_books_path(@library), class:'pull-right btn btn-primary btn-xs' %>
                <h4 class="m-b-0 text-white">Добавить новую книгу в <%=@library.name%></h4>
            </div>
            <div class="card-body">
                <%= form_for ([@library, @library.books.build]), {:multipart => true} do |f| %>
                  <div class="form-body">
                    <h3 class="card-title">Книга</h3>
                    <hr>
                  </div>
                  <% if @book.errors.any? %>   
                    <div class="alert alert-warning">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                      <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= t('validate_errors.error', count: @book.errors.count)%></h3> <% @book.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                    </div>     
                  <% end %>
                  <div class="row p-t-20">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :name, class: 'control-label' %>  <span class="text-danger">*</span> / <%= f.label :author, class: 'control-label' %>
                            <%= f.text_field :name, class: 'form-control', placeholder: "Название" %>
                            <small class="form-control-feedback"> Введите Название книги </small>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            
                            <%= f.text_field :author, class: 'form-control', placeholder: "Автор" %>
                            <small class="form-control-feedback"> Введите Авторов книги </small>
                        </div>
                    </div>
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :cipher, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :cipher, class: 'form-control', placeholder: "Шифр" %>
                            <small class="form-control-feedback"> Введите Шифр книги </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :price, class: 'control-label' %>
                            <%= f.text_field :price, class: 'form-control', placeholder: "00.00" %>
                            <small class="form-control-feedback"> Введите Цену книги </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :date, class: 'control-label' %>
                            <%= f.date_field :date, class: 'form-control', placeholder: "дд.мм.гггг" %>
                            <small class="form-control-feedback"> Введите Дату поступления книги в библиотеку </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :publ, class: 'control-label' %>
                            <%= f.text_field :publ, class: 'form-control', placeholder: "Издательство" %>
                            <small class="form-control-feedback"> Введите Название издательства </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :publ_y, class: 'control-label' %>
                            <%= f.number_field :publ_y, class: 'form-control', placeholder: "гггг", min: 1000, max: 2100, step: 1 %>
                            <small class="form-control-feedback"> Введите Год издания </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="form-actions">
                    <%= f.submit 'Сохранить',class: "pull-right btn btn-success" %>
                    <%= link_to 'Назад', library_books_path(@library), class:'btn btn-primary' %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
            	<div class="row">
			      <div class="col-md-9">
			        <h2><%=@book.name%></h2>
			      </div>
			      <div class="col-md-3 text-right">
			      	<%= link_to '', edit_library_book_path(@book.library,@book), class: "btn btn-outline-success ti-pencil", data: { pack: 'default' }  %>
            		<%= link_to '', [@book.library, @book], class: "btn btn-outline-danger ti-trash",
                    method: :delete,
                    data: { confirm: 'Вы уверены, что хотите удалить: "'+@book.name+'" и все что с ней связано?', pack: 'default' } %>
			      </div>
			    </div>
            	
            	<p><%=@book.author%> / <%=@book.publ%></p>
                <div class="row">
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Шифр</strong>
                        <br>
                        <p class="text-muted"><%=@book.cipher%></p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Год издания</strong>
                        <br>
                        <p class="text-muted"><%=@book.publ_y%></p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r"> <strong>Дата поступления</strong>
                        <br>
                        <p class="text-muted"><%=@book.date%></p>
                    </div>
                    <div class="col-md-3 col-xs-6"> <strong>Цена</strong>
                        <br>
                        <p class="text-muted"><%=@book.price%></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Выдать книгу</h4>
                <% if params['error_serch'] == "1" %>
            			<div class="alert alert-warning"> <i class="ti-user"></i> Абонент с читательским билетом <strong><%=params["number"]%></strong> не найден в <%=@book.library.name%>. Книга не выдана.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                        </div>
				<% end %>
                <%= form_for ([@book.library, @book.issues.build]), {:class => 'form'} do |f| %>
                    <div class="form-group">
                    	<%= f.label :number, 'Номер читательского билета' %>
                    	<div class="input-group">
                    		<div class="input-group-addon"><i class="ti-ticket"></i></div>
                        	<%= text_field_tag(:number, "",class: 'form-control', placeholder: 'XXXXXXX')  %>
                        </div>
                    </div>
                    <div class="form-group">
                    	<%= f.label :d_start, 'Дата выдачи' %>
                    	<div class="input-group">
                    		<div class="input-group-addon"><i class="ti-calendar"></i></div>
                        	<%= f.date_field :d_start, class: 'form-control', placeholder: "дд.мм.гггг", value: Time.now.strftime("%d.%m.%Y") %>
                        </div>
                    </div>
                    <div class="form-group">
                    	<%= f.label :d_end, 'Дата возврата' %>
                    	<div class="input-group">
                    		<div class="input-group-addon"><i class="ti-calendar"></i></div>
                        	<%= f.date_field :d_end, class: 'form-control', placeholder: "дд.мм.гггг" %>
                        </div>
                    </div>
                 	<%= f.hidden_field :book_id, value: @book.id %>
                    <%= f.submit 'Выдать', class: 'btn btn-success' %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Выдачи</h4>
                <div class="table-responsive">
                      <table id="TableDataodel" class="table table-bordered table-striped table-sm">
                        <thead>
                          <tr>
                            <th class="text-center" data-searchable="false">#</th>
                            <th class="text-center">Номер билета</th>
                            <th colspan="3">ФИО</th>
                            <th class="text-center">Выдача</th>
                            <th class="text-center">Возврат</th>
                            <th class="text-center" data-orderable="false" data-searchable="false"></th>
                          </tr>
                        </thead>
                        <tbody>
                            <% @book_issues.each do |book_issue| %>
                                <tr>
                                  <td class="text-center"><%= book_issue.id %></td>
                                  <td class="text-center"><%= book_issue.subscriber.number %></td>
                                  <td><%= book_issue.subscriber.sname %></td>
                                  <td><%= book_issue.subscriber.fname %></td>
                                  <td><%= book_issue.subscriber.mname %></td>
                                  <td class="text-center"><%= book_issue.d_start %></td>
                                  <td class="text-center"><%= book_issue.d_end %></td>
                                  <td class="text-center"><%= link_to '', library_subscriber_path(@book.library,book_issue.subscriber), class: "btn btn-outline-info ti-user", target:'_blank'  %> <%= link_to '', edit_library_issue_path(@book.library,book_issue), class: "btn btn-outline-success ti-pencil", target:'_blank'  %></td>
                                </tr>
                            <% end %>
                        </tbody>
                      </table>
                    </div>


                             
            </div>
        </div>
    </div>
</div>