config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :libraries do
	resources :books
	resources :workers
	resources :subscribers
	resources :issues
  end
 
  root 'libraries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :library
  has_many :issues
  has_many :books, through: :issues
  validates :number, presence: true
  validates :sname, presence: true
  validates :fname, presence: true
  validates :address, presence: true
  validates :phone, presence: true
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
	def index
		@library = Library.find(params[:library_id])
    	@subscribers = Subscriber.all
	end

	def show
		@library = Library.find(params[:library_id])
    	@subscriber = Subscriber.find(params[:id])
    	@issues = Issue.where(subscriber_id: params[:id])
	end

	def new
		@library = Library.find(params[:library_id])
		@subscriber = Subscriber.new
	end

	def edit
	  @library = Library.find(params[:library_id])
	  @subscriber = Subscriber.find(params[:id])
	end

	def create
		@library = Library.find(params[:library_id])
		@subscriber = @library.subscribers.create(subscriber_params)
		if @subscriber.valid?
			redirect_to library_subscriber_path(@library,@subscriber)
    	else
			render 'new'
		end
	end
		

	def update
	  @library = Library.find(params[:library_id])
	  @subscriber = Subscriber.find(params[:id])
	  if @subscriber.update(subscriber_params)
	    redirect_to library_subscriber_path(@library,@subscriber)
	  else
	    render 'edit'
	  end
	end

	def destroy
		@library = Library.find(params[:library_id])
		@subscriber = @library.subscribers.find(params[:id])
		@subscriber.destroy
		redirect_to library_subscribers_path(@library)
	end

	private
	  def subscriber_params
	    params.require(:subscriber).permit(:fname, :sname, :mname, :number, :phone, :address)
	  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <%= link_to 'Назад', library_subscriber_path(@library,@subscriber), class:'pull-right btn btn-primary btn-xs' %>
                <h4 class="m-b-0 text-white">Редактировать читателя</h4>
            </div>
            <div class="card-body">
                <%= form_for ([@library, @subscriber]) do |f| %>
                  <div class="form-body">
                    <h3 class="card-title">Читатель <%= @subscriber.fname%> <%= @subscriber.sname%></h3>
                    <hr>
                  </div>
                  <% if @subscriber.errors.any? %>   
                    <div class="alert alert-warning">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                      <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= t('validate_errors.error', count: @subscriber.errors.count)%></h3> <% @subscriber.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                    </div>     
                  <% end %>
                  <div class="row p-t-20">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :number, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :number, class: 'form-control', placeholder: "0000000" %>
                            <small class="form-control-feedback"> Введите номер билета читателя </small>
                        </div>
                    </div>
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :fname, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :fname, class: 'form-control', placeholder: "Иван" %>
                            <small class="form-control-feedback"> Введите Имя читателя </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :sname, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :sname, class: 'form-control', placeholder: "Иванов" %>
                            <small class="form-control-feedback"> Введите Фамилию читателя </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                            <%= f.label :mname, class: 'control-label' %>
                            <%= f.text_field :mname, class: 'form-control', placeholder: "Иванов" %>
                            <small class="form-control-feedback"> Введите Отчество читателя </small>
                        </div>
                      </div>
                      <!--/span-->
                      <div class="col-md-6">
                          <div class="form-group">
                              <%= f.label :phone, class: 'control-label' %> <span class="text-danger">*</span>
                              <%= f.phone_field :phone, class: 'form-control', placeholder: "7ХХХХХХХХХХ" %>
                              <small class="form-control-feedback"> Введите Телефон читателя в формате 7ХХХХХХХХХХ</small>
                          </div>
                      </div>
                      <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="row">
                      <div class="col-md-12">
                          <div class="form-group">
                              <%= f.label :address, class: 'control-label' %> <span class="text-danger">*</span>
                              <%= f.text_field :address, class: 'form-control', placeholder: "Индекс, Регион, Город, Адрес" %>
                              <small class="form-control-feedback"> Введите Адрес читателя</small>
                          </div>
                      </div>
                  </div>
                  
                  <div class="form-actions">
                    <%= link_to 'Назад', library_subscriber_path(@library,@subscriber), class:'btn btn-primary' %>
                    <%= f.submit 'Сохранить',class: "pull-right btn btn-success" %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/subscribers/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-8">
        <h2>Читатели Библиотеки №<%=@library.number%></h2>
      </div>
      <div class="col-md-4 text-right">

        <%= link_to '', new_library_subscriber_path(@library), class: "btn btn-outline-success ti-plus" %>
        <%= link_to 'Назад', library_path(@library), class:'btn btn-outline-primary' %>
      </div>
    </div>
    <div class="table-responsive m-t-40">
      <table id="TableDataodel" class="table table-bordered table-striped table-sm">
        <thead>
          <tr>
            <th class="text-center" data-searchable="false">#</th>
            <th class="text-center">Номер билета</th>
            <th colspan="3">ФИО</th>
            <th class="text-center">Телефон</th>
            <th>Адрес</th>
            <th class="text-center" data-orderable="false" data-searchable="false"></th>
          </tr>
        </thead>
        <tbody>
          <% @library.subscribers.each do |subscriber| %>
            <tr>
              <td class="text-center"><%= subscriber.id %></td>
              <td class="text-center"><%= subscriber.number %></td>
              <td><%= subscriber.sname %></td>
              <td><%= subscriber.fname %></td>
              <td><%= subscriber.mname %></td>
              <td class="text-center"><%= subscriber.phone %></td>
              <td><%= subscriber.address %></td>
              <td class="text-center"><%= link_to '', library_subscriber_path(@library,subscriber), class: "btn btn-outline-info ti-book", target:'_blank' %>
              <%= link_to '', [subscriber.library, subscriber], class: "btn btn-outline-danger ti-trash",
                      method: :delete,
                      data: { confirm: 'Вы уверены, что хотите удалить читателя: "'+subscriber.sname+'" и все что с ним связано?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/subscribers/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header bg-info">
                <%= link_to 'Назад', library_subscribers_path(@library), class:'pull-right btn btn-primary btn-xs' %>
                <h4 class="m-b-0 text-white">Добавить нового читателя</h4>
            </div>
            <div class="card-body">

                  <h3 class="card-title">Читатель</h3>
                  <hr>
                <%= form_for ([@library, @library.subscribers.build]) do |f| %>
                  
                  <% if @subscriber.errors.any? %>   
                    <div class="alert alert-warning">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                      <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= t('validate_errors.error', count: @subscriber.errors.count)%></h3> <% @subscriber.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                    </div>     
                  <% end %>
                  <div class="row p-t-20">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :number, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :number, class: 'form-control', placeholder: "0000000" %>
                            <small class="form-control-feedback"> Введите номер билета читателя </small>
                        </div>
                    </div>
                  </div>
                  <div class="row p-t-20">
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :fname, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :fname, class: 'form-control', placeholder: "Иван" %>
                            <small class="form-control-feedback"> Введите Имя читателя </small>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= f.label :sname, class: 'control-label' %> <span class="text-danger">*</span>
                            <%= f.text_field :sname, class: 'form-control', placeholder: "Иванов" %>
                            <small class="form-control-feedback"> Введите Фамилию читателя </small>
                        </div>
                    </div>
                    <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                            <%= f.label :mname, class: 'control-label' %>
                            <%= f.text_field :mname, class: 'form-control', placeholder: "Иванов" %>
                            <small class="form-control-feedback"> Введите Отчество читателя </small>
                        </div>
                      </div>
                      <!--/span-->
                      <div class="col-md-6">
                          <div class="form-group">
                              <%= f.label :phone, class: 'control-label' %> <span class="text-danger">*</span>
                              <%= f.phone_field :phone, class: 'form-control', placeholder: "7ХХХХХХХХХХ" %>
                              <small class="form-control-feedback"> Введите Телефон читателя в формате 7ХХХХХХХХХХ</small>
                          </div>
                      </div>
                      <!--/span-->
                  </div>
                  <!--/row-->
                  <div class="row">
                      <div class="col-md-12">
                          <div class="form-group">
                              <%= f.label :address, class: 'control-label' %> <span class="text-danger">*</span>
                              <%= f.text_field :address, class: 'form-control', placeholder: "Индекс, Регион, Город, Адрес" %>
                              <small class="form-control-feedback"> Введите Адрес читателя</small>
                          </div>
                      </div>
                  </div>
                  
                  <div class="form-actions">
                    <%= link_to 'Назад', library_subscribers_path(@library), class:'btn btn-primary' %>
                    <%= f.submit 'Сохранить',class: "pull-right btn btn-success" %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/subscribers/show.html.erb
<div class="row">
    <!-- Column -->
    <div class="col-lg-4 col-xlg-3 col-md-5">
        <div class="card">
            <div class="card-body">
                    <h4 class="card-title"><%= @subscriber.sname%> <%= @subscriber.fname%> <%= @subscriber.mname%></h4>
                    <h6 class="card-subtitle"><%= @subscriber.number%><br><%= @library.name%></h6>
                    <hr>
                    <center><%= link_to '', edit_library_subscriber_path(@library,@subscriber), class: " btn btn-outline-success ti-pencil" %> <%= link_to '', [@subscriber.library, @subscriber], class: "btn btn-outline-danger ti-trash",
                      method: :delete,
                      data: { confirm: 'Вы уверены, что хотите удалить читателя: "'+@subscriber.sname+'" и все что с ним связано?' } %></center>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <small class="text-muted">Телефон</small>
                <h6><%= @subscriber.phone%></h6>
                <small class="text-muted p-t-30 db">Адрес</small>
                <h6><%= @subscriber.address%></h6>
                <div class="map-box" id="map-for-subscriber" style="height: 150px;">
                </div>
                <script type="text/javascript">
                    ymaps.ready(init);
                    function init() {
                        var myMap = new ymaps.Map('map-for-subscriber', {
                            center: [55.753994, 37.622093],
                            zoom: 9
                        });
                        ymaps.geocode('<%= @subscriber.address%>', {
                            results: 1
                        }).then(function (res) {
                                var firstGeoObject = res.geoObjects.get(0),
                                coords = firstGeoObject.geometry.getCoordinates(),
                                bounds = firstGeoObject.properties.get('boundedBy');
                                firstGeoObject.options.set('preset', 'islands#darkBlueDotIconWithCaption');
                                firstGeoObject.properties.set('iconCaption', firstGeoObject.getAddressLine());
                                myMap.geoObjects.add(firstGeoObject);
                                myMap.setBounds(bounds, {
                                    checkZoomRange: true
                                });
                            });
                    }
                </script>
            </div>
        </div>
    </div>
    <!-- Column -->
    <!-- Column -->
    <div class="col-lg-8 col-xlg-9 col-md-7">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Выдать книгу читателю <%=@subscriber.fname+' '+@subscriber.sname%></h4>
                <% if params['error_serch'] == "1" %>
                        <div class="alert alert-warning"> <i class="ti-user"></i> Книга с Шифром <strong><%=params["cipher"]%></strong> не найдена в <%=@library.name%>. Книга не выдана.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                        </div>
                <% end %>
                <%= form_for ([@library, @subscriber.issues.build]), {:class => 'form'} do |f| %>
                    <div class="form-group">
                        <%= f.label :number, 'Шифр книги' %>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="ti-book"></i></div>
                            <%= text_field_tag(:cipher, "",class: 'form-control')  %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.label :d_start, 'Дата выдачи' %>
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="ti-calendar"></i></div>
                                    <%= f.date_field :d_start, class: 'form-control', placeholder: "дд.мм.гггг", value: Time.now.strftime("%d.%m.%Y") %>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.label :d_end, 'Дата возврата' %>
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="ti-calendar"></i></div>
                                    <%= f.date_field :d_end, class: 'form-control', placeholder: "дд.мм.гггг" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                    <%= f.hidden_field :subscriber_id, value: @subscriber.id %>
                    <%= f.submit 'Выдать', class: 'btn btn-success' %>
                <% end %>
            </div>
        </div>
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Выдачи</h4>

                <div class="table-responsive">
                      <table id="TableDataodel" class="table table-bordered table-striped table-sm">
                        <thead>
                          <tr>
                            <th class="text-center">Шифр</th>
                            <th>Книга</th>
                            <th class="text-center">Выдача</th>
                            <th class="text-center">Возврат</th>
                            <th class="text-center" data-orderable="false" data-searchable="false"></th>
                          </tr>
                        </thead>
                        <tbody>
                            <% @issues.each do |issue| %>
                                <tr>
                                  <td class="text-center"><%= issue.book.cipher %></td>
                                  <td><%= issue.book.name %></td>
                                  <td class="text-center"><%= issue.d_start %></td>
                                  <td class="text-center"><%= issue.d_end %></td>
                                  <td class="text-center"><%= link_to '', edit_library_issue_path(@library,issue), class: "btn btn-outline-success ti-pencil", target:'_blank'  %></td>
                                </tr>
                            <% end %>
                        </tbody>
                      </table>
                    </div>                             
            </div>
        </div>
    </div>
    <!-- Column -->
</div>